"""
This is a setup.py script generated by py2applet

Usage:
    python3.6 setup.py py2app
"""

from setuptools import setup

# Additional stdlib imports needed for locating pyo's bundled dylibs.
import glob, importlib.util, pathlib, sys

# Increase recursion depth limit for py2app/modulegraph build phase
# (Workaround for RecursionError in modulegraph on some Python versions)
sys.setrecursionlimit(4000) # Default is often 1000

# Locate the directory where pyo is installed and collect every lib*.dylib it
# ships (libFLAC, libogg, libsndfile, etc.).  This ensures py2app copies them
# into the final .app bundle under Contents/Frameworks so they are available at
# run-time on users' machines.
spec = importlib.util.find_spec('pyo')
if spec is not None:
    _pyo_dir = pathlib.Path(spec.origin).parent
    PYO_DYLIBS = [str(p) for p in _pyo_dir.glob('lib*.dylib')]
else:
    PYO_DYLIBS = []  # fallback – pyo not found; build will still succeed

APP = ['Cecilia5.py']
APP_NAME = 'Cecilia5'
DATA_FILES = ['Resources/']
OPTIONS = {
    "iconfile": "Resources/Cecilia5.icns",
    "argv_emulation": False,
    "includes": "wx.adv,wx.html,wx.xml,pyo",
    "packages": ["pyo", "zmq", "ruamel"],
    "excludes": ["zmq"],
    # place the extra dylibs here ⬇
    "frameworks": PYO_DYLIBS,      # <— instead of "resources"
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

